name: Generate ASCII Artwork Multiple Jobs

on: push

env:
    DRAGON_ARTIFACT_NAME: dragon-text-file
    DRAGON_FILE_NAME: dragon.txt

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Use Variables and Secrets
          run: echo repo login --userName=${{ vars.REPO_USERNAME }} and --Password=${{ secrets.REPO_PASSWORD }}
          
        - name: Install Cowsay program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay Cmd
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> "$DRAGON_FILE_NAME"

        - name: Upload Dragon Text
          uses: actions/upload-artifact@v4
          with:
            name: ${{ env.DRAGON_ARTIFACT_NAME }}
            path: ${{ env.DRAGON_FILE_NAME }}

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon Text
          uses: actions/download-artifact@v5
          with:
            name: ${{ env.DRAGON_ARTIFACT_NAME }}

        - name: Test File Exists
          run: grep -i "dragon" $DRAGON_FILE_NAME

    deploy_job_3:
        if: github.ref == 'refs/heads/main'
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
        - name: Download Dragon Text
          uses: actions/download-artifact@v5
          with:
            name: ${{ env.DRAGON_ARTIFACT_NAME }}

        - name: Read File
          run: cat ${{ env.DRAGON_FILE_NAME }}

        - name: Deploy
          run: echo "Deploying.... ..."